# Alpine for minimal size -> less vulnerabilities
FROM python:3.14-alpine

WORKDIR /usr/src/EventFlow

# Disable .pyc files and make stdout/err writes unbuffered
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install os dependencies
RUN apk add --no-cache \
  postgresql-dev \
  gcc \
  musl-dev \
  vim

# Install python dependencies
RUN pip install --upgrade pip
COPY ./requirements_django.txt .
RUN pip install -r requirements_django.txt

# Project code will be inserted as Volume
VOLUME /usr/src/EventFlow

RUN addgroup --system --gid 1000 app && adduser --system -u 1000 -G app app

USER app
