# Generated by Django 6.0.5 on 2026-06-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=160)),
                ('password', models.CharField(max_length=100)),
                ('firmenname', models.CharField(max_length=200)),
                ('firmensitzLand', models.CharField(max_length=50)),
                ('firmensitzOrt', models.CharField(max_length=170)),
                ('firmensitzStraße', models.CharField(max_length=85)),
                ('firmensitzHausnummer', models.IntegerField()),
                ('telefon', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
            ],
        ),
    ]
