# Generated by Django 6.0.5 on 2026-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentifizierung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angemeldet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
