# Generated by Django 6.0.5 on 2026-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('start_datum', models.DateField()),
                ('end_datum', models.DateField()),
                ('ort', models.CharField(max_length=200)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
