# Generated by Django 6.0.5 on 2026-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='timeslots',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
