# Generated by Django 6.0.5 on 2026-06-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltungen', '0002_veranstaltung_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veranstaltung',
            name='timeslots',
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('ende', models.TimeField()),
                ('dauer', models.PositiveIntegerField()),
                ('kategorie', models.CharField(max_length=200)),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='veranstaltungen.veranstaltung')),
            ],
        ),
    ]
